# Generated by Django 5.0.2 on 2024-02-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_perishable', models.BooleanField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
