# Generated by Django 5.0.2 on 2024-02-21 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_slug_alter_products_category'),
        ('suppliers', '0002_alter_suppliers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliers')),
            ],
            options={
                'verbose_name': 'Forcenedor do Produto',
                'verbose_name_plural': 'Fornecedores dos Produtos',
                'unique_together': {('supplier', 'product')},
            },
        ),
        migrations.AddField(
            model_name='products',
            name='suppliers',
            field=models.ManyToManyField(through='products.SupplierProduct', to='suppliers.suppliers'),
        ),
    ]
